# compose.yaml
# compose file for the ABP plugin
# written by Aaron Krapes
# Feb 10, 2026

services:
  abeonasec-plugin-abp:
    container_name: abeonasec-plugin-abp
    environment:
    - PORT=8003
    devices:
      - nvidia.com/gpu=all
    networks:
    - plugin-abp-bridge
    - internal # needs to communicate inside the pod
networks:
  internal: {}
  plugin-abp-bridge:
    external: true # use pre-existing network